name: wave_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  dio: ^5.0.3
  just_audio: ^0.9.33
  cached_network_image: ^3.2.3
  json_serializable: ^6.6.2
  path_provider: ^2.1.5
  go_router: ^14.6.1
  json_annotation: ^4.9.0
  provider: ^6.1.2
  url_launcher: ^6.0.9
  firebase_core: ^3.8.1  
  firebase_auth: ^5.3.4
  google_sign_in: ^6.0.0

  marquee: ^2.3.0
  audioplayers: ^6.1.0
  http: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
