name: wave_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^5.0.3
  dio: ^5.0.3
  just_audio: ^0.9.33
  cached_network_image: ^3.2.3
  json_serializable: ^6.6.2
  path_provider: ^2.1.5
  go_router: ^14.6.1

dev_dependencies:
  build_runner: ^2.4.5
  json_annotation: ^4.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/music.json
    - assets/audios/
