// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvFEX1U6ZT0P-5jFoGWAnqGPZsMOV_0h0',
    appId: '1:779306557409:web:91cdb585ac78ba6fe33ca0',
    messagingSenderId: '779306557409',
    projectId: 'wave-flutter-54598',
    authDomain: 'wave-flutter-54598.firebaseapp.com',
    storageBucket: 'wave-flutter-54598.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNQVGpW9sXVdL9ifIwk179ue-YlC6g6w',
    appId: '1:779306557409:android:f12c477cb57c60afe33ca0',
    messagingSenderId: '779306557409',
    projectId: 'wave-flutter-54598',
    storageBucket: 'wave-flutter-54598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGr_Bzyj2zgHHcVNWH1MZkfPMiq40aAzM',
    appId: '1:779306557409:ios:21801f5e9c0692ade33ca0',
    messagingSenderId: '779306557409',
    projectId: 'wave-flutter-54598',
    storageBucket: 'wave-flutter-54598.firebasestorage.app',
    iosBundleId: 'com.example.waveFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGr_Bzyj2zgHHcVNWH1MZkfPMiq40aAzM',
    appId: '1:779306557409:ios:21801f5e9c0692ade33ca0',
    messagingSenderId: '779306557409',
    projectId: 'wave-flutter-54598',
    storageBucket: 'wave-flutter-54598.firebasestorage.app',
    iosBundleId: 'com.example.waveFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvFEX1U6ZT0P-5jFoGWAnqGPZsMOV_0h0',
    appId: '1:779306557409:web:a228889a58b71bd1e33ca0',
    messagingSenderId: '779306557409',
    projectId: 'wave-flutter-54598',
    authDomain: 'wave-flutter-54598.firebaseapp.com',
    storageBucket: 'wave-flutter-54598.firebasestorage.app',
  );
}
